all: coolkidgame

coolkidgame: main.cpp Game.cpp Board.cpp Space.cpp Player.cpp Token.cpp NumberDie.cpp OperationDie.cpp EvenOddSpace.cpp NumberSpace.cpp ShortcutSpace.cpp EndlessLoopSpace.cpp ExitSpace.cpp
		g++ -std=c++17 -Wall -o coolkidgame main.cpp Game.cpp Board.cpp Space.cpp Player.cpp Token.cpp NumberDie.cpp OperationDie.cpp EvenOddSpace.cpp NumberSpace.cpp ShortcutSpace.cpp EndlessLoopSpace.cpp ExitSpace.cpp

clean: 
		rm -f coolkidgame